# Generated by Django 6.0.1 on 2026-02-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentanalysis',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='csv_uploads/'),
        ),
    ]
